#!/usr/bin/env bash
./pallache <<EOF |
x=1
x
cos(x-1)==1
5+5==10
5-5==0
-5+5==0
-5--5==0
5*pi-1==pi*5-1
(4*3+1)**2==pow(13,2)
2**3==pow(2,3)
5!==120
5!**2==120**2
5!+2==122
5!-2==118
inf==1/0
delvar x
ans
round(sin(pi)!)
3**3**3==(2+1)**((2!+1)**sqrt(pow(3,2)))
1.-.5--.5
b=1
b+b==2
b-b==0
-b+b==0
-b--b==0
delvar(b)
EOF
cat -n | awk '{print $1+2" "$2" "$3}'
exit 0
